name: Hello World. workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        run: |
          echo "Cloning repository  "
          git clone https://github.com/${(github.repository)}/gha-cicd-pipeline-shivangi.git myfolder
          cd myfolder && ls -la
